### ISSUE TITLE
VSCode WSL remote doesn't work when SymCrypt OpenSSL engine is set as default

### ISSUE THREAD

**Issue by mlindgren** [microsoft/SymCrypt-OpenSSL#11]
When SymCrypt-OpenSSL is set as the default engine for all algorithms in via OpenSSL.cnf, VSCode Remote for WSL fails to connect with the following errors:

```
[2021-09-16 16:07:30.426] [renderer1] [info] [remote-connection][ExtensionHost][91019…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-09-16 16:07:30.426] [renderer1] [info] [remote-connection][ExtensionHost][91019…][reconnect] resolving connection...
[2021-09-16 16:07:34.677] [renderer1] [info] [remote-connection][Management   ][04ee5…][reconnect] connecting to <IP removed>:39209...
[2021-09-16 16:07:34.679] [renderer1] [info] [remote-connection][ExtensionHost][91019…][reconnect] connecting to <IP removed>:39209...
[2021-09-16 16:07:34.844] [renderer1] [info] [remote-connection][Management   ][04ee5…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2021-09-16 16:07:34.845] [renderer1] [error] {"isTrusted":true}
[2021-09-16 16:07:34.851] [renderer1] [error] [remote-connection][Management   ][04ee5…][reconnect][<IP removed>:39209] received error control message when negotiating connection. Error:
[2021-09-16 16:07:34.852] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at W (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:154700)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:145469
    at l.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at n.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)
    at u._receiveMessage (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21798)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20841
    at l.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at b.acceptChunk (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186
    at vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:140524
    at l.fire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at FileReader._fileReader.onload (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:139084)
[2021-09-16 16:07:34.852] [renderer1] [error] [remote-connection][Management   ][04ee5…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2021-09-16 16:07:34.852] [renderer1] [error] Error: Connection error: Unknown reconnection token
```

Compiling with tracing enabled does not yield any errors or warnings in the SCOSSL log:

```
mitch@MITCHL-Z420:~$ rg ERROR /tmp/scossl.log
mitch@MITCHL-Z420:~$ rg WARN /tmp/scossl.log
```

openssl.cnf changes:
```
[ openssl_def ]
engines = engine_section

[ engine_section ]
symcrypt = symcrypt_section

[ symcrypt_section ]
engine_id = symcrypt
dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/libsymcryptengine.so
default_algorithms = ALL
init = 1
```

Unfortunately I haven't found a good way to debug this yet.

**Comment by chrmarti** [comment]
"Unknown reconnection token" could indicate that the VS Code Server was restarted and VS Code tries to reestablish the interrupted connection without being aware of that. Another possibility would be that the connection terminated unexpectedly, but the VS Code Server somehow thinks that it was regularly terminated (or timed out) and it deleted the connection information, not recognizing the 'reconnection token' when VS Code tries to reconnect.

What seems clear is that there was a connection and that was somehow interrupted. At the time of the error VS Code is trying to reestablish that connection, but the server does not recognize the reconnection token anymore. (Reconnection tokens identify a remote session and help resuming sessions after network connections were interrupted.)

**Comment by samuel-lee-msft** [comment]
I wasn't able to replicate the error - waiting for Mitch to confirm whether it is still an issue for him.

**Comment by mlindgren** [comment]
Confirmed that this no longer reproes for me (sorry for the delay)
